### ISSUE TITLE
可以简化下grpc-consul的使用方式, 让client/server专注业务逻辑

### ISSUE THREAD

**Issue by lincuss** [Liu-Alan/Grpc-Consul#1]
代码可以参考下
https://github.com/FollowmeTech/fm.consulinterop

**Comment by Liu-Alan** [comment]
您说的很对，谢谢你的建议，我这个只是做个测试，提供一种简单思路，如果要在开发中使用，需对grpc和consul做封装优化，使使用起来更方便
